### ISSUE TITLE
Failed to start a review project

### ISSUE THREAD

**Issue by ddxgz** [JoaoFelipe/snowballing#4]
Hi, it returned to me the error information shown below when I run `snowballing start review1`. And I found there's no `example` directory under the snowballing package after pip installation.  

- OS: MacOS 10.13
- Python version: 3.6
- Env: Python venv

```
Traceback (most recent call last):
  File "/Users/pc/.virtualenvs/reviews1/bin/snowballing", line 11, in <module>
    sys.exit(main())
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/snowballing/__init__.py", line 94, in main
    args.func(args)
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/snowballing/__init__.py", line 36, in start
    recursive_copy('../example', args.path)
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/snowballing/__init__.py", line 30, in recursive_copy
    fil.write(resource(origin))
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/snowballing/__init__.py", line 13, in resource
    content = resource_string(__name__, filename)
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1214, in resource_string
    self, resource_name
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1456, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1576, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pc/.virtualenvs/reviews1/lib/python3.6/site-packages/snowballing/../example'
```

**Comment by JoaoFelipe** [comment]
Thank you for reporting the bug! I'll try to fix it soon. In the meantime, copy the example folder from https://github.com/JoaoFelipe/snowballing/tree/master/example and rename it to review1

As an alternative, you can try to install it from the source:
```
git clone https://github.com/JoaoFelipe/snowballing.git
pip install -e snowballing
```

**Comment by ddxgz** [comment]
Thanks for your quick response. Copy the example folder works for me.

I tried to install from source, got an error information says:
```Directory 'snowballing' is not installable. File 'setup.py' not found.```

but `setup.py` actually exists in the directory. I'll try to find if the problem is caused by my settings.
